### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by simuons** [simuons/rules_clojure#14]
Repo has test which can be run with `bazel test //...` but there is no CI

**Comment by markdingram** [comment]
See comment here re Github Actions https://github.com/simuons/rules_clojure/pull/12#issuecomment-659273938

**Comment by simuons** [comment]
Hi @markdingram if you could send a PR that would be awesome.

**Comment by simuons** [comment]
Initial CI was set up via github actions https://github.com/simuons/rules_clojure/blob/master/.github/workflows/ci.yml
Will be improved as needed
