### ISSUE TITLE
Support bazel 2.0

### ISSUE THREAD

**Issue by marplesoft** [simuons/rules_clojure#4]
Currently under bazel 2.0 I get the following:
```
ERROR: /private/var/tmp/_bazel_[username]/1f8310a13b66369d223611f315edd44f/external/rules_clojure/runtime.bzl:2:5: Traceback (most recent call last):
	File "/Users/[username]/Dev/v1monorepo/WORKSPACE", line 145
		clojure_runtime()
	File "/private/var/tmp/_bazel_[username]/1f8310a13b66369d223611f315edd44f/external/rules_clojure/runtime.bzl", line 2, in clojure_runtime
		native.maven_jar
no native function or rule 'maven_jar'
```
See: https://github.com/bazelbuild/bazel/issues/6799

**Comment by marplesoft** [comment]
Happy to try to get this working and send a PR if you're interested. 

I modified the use of `native.maven_jar` to use `jvm_maven_import_external` from `@bazel_tools//tools/build_defs/repo:jvm.bzl` which worked. Thought not sure if this breaks use in bazel 1.x. 

Then I had other issues with importing `rules.bzl` into my workspace because it used labels not qualified with the repo name. This thread explained why you have to qualify all labels with `@rules_clojure`: https://groups.google.com/forum/#!topic/bazel-discuss/qNuyIu-akq8
Not sure if this later issue was also a bazel 2.0 change or not.

**Comment by simuons** [comment]
Oh sorry I've missed that one. If you could send a PR that would be great. If not I'll take care of this  on weekend.

**Comment by simuons** [comment]
I felt guilty for not responding in timely manner so I changed maven_jar myself. I'll take a look to label qualifiers. Thanks for reporting.

**Comment by marplesoft** [comment]
Great, thanks. I have a hacked-up local copy that mostly works and happy to work on a PR. Regarding label qualifiers, what I did, and what appears to be the recommended solution, is to qualify all non-relative labels with `@rules_clojure`, so like [here](https://github.com/simuons/rules_clojure/blob/master/rules.bzl#L16) would become

    toolchains = ["@rules_clojure//rules:toolchain_type"],

**Comment by marplesoft** [comment]
Another issue, which isn't this problem of this project, is that `org.clojure:clojure` and `org.clojure:spec.alpha` and `org.clojure:core.specs.alpha` have circular dependencies between them that bazel rejects. I've resolved this in an ugly way by doing this:

```
load("@rules_jvm_external//:defs.bzl", "maven_install")
load("@rules_jvm_external//:specs.bzl", "maven")

maven_install(
    artifacts = [
        "com.amazonaws:amazon-kinesis-client:1.8.4", // for example
        ...
        maven.artifact(
            "org.clojure",
            "clojure",
            "1.10.1",
            exclusions = [
                "org.clojure:core.specs.alpha",
                "org.clojure:spec.alpha",
            ]
        ),
        maven.artifact(
            "org.clojure",
            "spec.alpha",
            "0.2.176",
            exclusions = [
                "org.clojure:clojure"
            ]
        ),
        maven.artifact(
            "org.clojure",
            "core.specs.alpha",
            "0.2.44",
            exclusions = [
                "org.clojure:clojure"
            ]
        )
    ],
    repositories = [
        "https://repo1.maven.org/maven2",
        "https://repo.clojars.org"
    ],
)
```

Just mentioning here in case it helps others.

**Comment by simuons** [comment]
Repo now has ci which build and test against bazel 3.4.1
Probably toolchain needs to be improved to accept clojure deps from different loaders. 
I home I'll make this change some time in near future.
