### ISSUE TITLE
Program produced by `bazel build` isn't runnable?

### ISSUE THREAD

**Issue by stevana** [simuons/rules_clojure#54]
Maybe I'm misunderstanding how this is supposed to work, but after doing `bazel build` it says `bazel-bin/src/p/p` was produced, but when I try to run that program I get: `./p: 1: ./p: ../local_jdk/bin/java: not found`.

`bazel run` works though.

Is this really how it ought to be?

**Comment by stevana** [comment]
This problem is fixed in the more active fork: https://github.com/griffinbank/rules_clojure

**Comment by simuons** [comment]
Sorry for delay. It is supposed to work as https://docs.bazel.build/versions/master/be/java.html#java_binary
Thanks for reporting. I'll take a look (even it's fixed in a fork).
